<dl class="dl_42">
                      <dt><a title="[field:title/]" href="[field:arcurl/]" target="_blank">
                    <img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a></dt>
                        <dd>
                    <h5><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h5>
                        <q>[field:pubdate function="GetDateMK(@me)"/]</q>
                        <p>[field:description function="cn_substr(@me,200)"/]...</p>
                                </dd>
                            </dl>
                            <div class="clear">
                            </div>