<li><a href="[field:arcurl/]" title="[field:title/]" target="_blank"> <img class="lazyimg" src="/templets/yan/images/grey.gif" _src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a><span><a href="[field:arcurl/]" title="[field:title/]" target="_blank"

                                    class="red">[field:title/]</a><a  href="" target="_blank"  title="购买咨询">购买咨询</a></span></li>