<?php
$z[0]=Array("title","",58,72);
$z[1]=Array("arcurl","",80,95);
$z[2]=Array("litpic","",149,164);
$z[3]=Array("title","",171,185);
$z[4]=Array("title","",194,208);
$z[5]=Array("arcurl","",302,317);
$z[6]=Array("title","",326,340);
$z[7]=Array("title","",358,372);
$z[8]=Array("pubdate","",424,466);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",513,563);
$z[9][4]['function']="cn_substr(@me,250)";

?>