<?php
$z[0]=Array("title","",66,80);
$z[1]=Array("arcurl","",88,103);
$z[2]=Array("litpic","",169,184);
$z[3]=Array("title","",191,205);
$z[4]=Array("title","",214,228);
$z[5]=Array("arcurl","",330,345);
$z[6]=Array("title","",354,368);
$z[7]=Array("title","",386,400);
$z[8]=Array("pubdate","",450,492);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",537,587);
$z[9][4]['function']="cn_substr(@me,250)";

?>