<dl class="dl_2">

                                <dt><a href="[field:arcurl/]" target="_blank"

                                    title="[field:title/]">

                                    <img src="[field:litpic/]"

                                        title="[field:title/]" alt="[field:title/]" /></a></dt>

                                <dd>

                                    <a href="[field:arcurl/]" target="_blank" title="[field:title/]">

                                        [field:title/]</a></dd>

                            </dl>