<dl class="clearfix">
          <dt><a href="[field:arcurl/]" title="[field:title/]" target="_blank"> <img class="lazyimg" src="/templets/yan/images/grey.gif" _src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a></dt>
          <dd>
            <h6> <a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h6>
            <p> [field:description function="cn_substr(@me,150)"/]......</p>
          </dd>
        </dl>