<?php
$z[0]=Array("global","(@me>1)? @me='sk_hide':@me='';",28,115);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","@me=@me;",127,192);
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("litpic","",227,242);
$z[3]=Array("title","",249,289);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("id","",323,358);
$z[4][4]['function']="getbody(@me)";
$z[5]=Array("typelink","",430,447);

?>