<div class="goods_ltcontent [field:global name=autoindex runphp='yes'](@me>1)? @me='sk_hide':@me='';[/field:global]" id="goods_[field:global name=autoindex runphp='yes']@me=@me;[/field:global]">
<div class="ltctimg"><img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" /></div>
<div class="ltctct">
[field:id function='getbody(@me)'/]
</div>
  {dede:type typeid='167'} <a class="margin-big-bottom" href="[field:typelink/]"> [MORE + ]</a>{/dede:type} </p>