<?php
$z[0]=Array("title","",61,75);
$z[1]=Array("arcurl","",83,98);
$z[2]=Array("litpic","",148,163);
$z[3]=Array("title","",170,184);
$z[4]=Array("title","",193,207);
$z[5]=Array("arcurl","",289,304);
$z[6]=Array("title","",313,327);
$z[7]=Array("title","",345,359);
$z[8]=Array("pubdate","",397,439);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",472,522);
$z[9][4]['function']="cn_substr(@me,250)";

?>