<li class="cooperation">
                <span><a  id="{dede:field name='id'/}" href="{dede:field name='typeurl'/}">
                             {dede:field name='typename'/}
                      </a>
                </span>
                <ul>
                  <span><a href="javascript:void(0)">护理</a></span>
                  {dede:channel type='son' noself='yes'}
                  <li><a href="[field:typelink/]">[field:typename/]</a></li>
 <!--                  <li><a href="#">护理等级</a></li>
                  <li><a href="#">护理特色</a></li>
                  <li><a href="#">护理辅助设施</a></li>
                  <li><a href="#">健康管理</a></li>
                  <li><a href="#">营养膳食</a></li>
                  <li><a href="#">安全保障</a></li> -->
                  {/dede:channel}
                </ul>
              </li>