<?php
$z[0]=Array("field","",56,79);
$z[0][4]['name']="id";
$z[1]=Array("field","",87,115);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",148,177);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n <!--                  <li><a href=\"#\">护理等级</a></li>\r\n                  <li><a href=\"#\">护理特色</a></li>\r\n                  <li><a href=\"#\">护理辅助设施</a></li>\r\n                  <li><a href=\"#\">健康管理</a></li>\r\n                  <li><a href=\"#\">营养膳食</a></li>\r\n                  <li><a href=\"#\">安全保障</a></li> -->\r\n                  ",344,852);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>