<span style="font-size: 24px;font-weight: bold;">关于我们</span>
<span id="span">About</span>
<a  href="[field:arcurl/]"  style="float: right; color: #c2c2c2; font-size: 14px;">NEWS+</a>
</div>
<p class="index_about">
  [field:id runphp=’yes’] $aid = @me; $row = $GLOBALS[‘dsql’]->GetOne(“Select body From `2d30_addonarticle` where aid=’$aid’ “); @me = cn_substr(strip_tags(“{$row[‘body’]}”),960);[/field:id]…
</p>