<dl class="clearfix">
        <dt><a href="[field:arcurl/]" title="[field:title/]" target="_blank"> <img class="lazyimg" src="/templets/yan/images/grey.gif" _src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a></dt>
        <dd>
          <h6><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h6>
          <p>[field:description function="cn_substr(@me,250)"/]...</p>
          <span><a href="[field:arcurl/]" title="查看详情" target="_blank"><img src="/templets/yan/images/btn6.gif" alt="查看详情" title="查看详情" /></a></span> </dd>
      </dl>