<dl class="dl_42">

                                <dt><a title="[field:title/]" href="[field:arcurl/]" target="_blank">

                                    <img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a></dt>

                                <dd>

                                    <h5><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h5>

                                    <q>[field:title/]</q>

                                    <p>[field:description function="cn_substr(@me,250)"/]...</p>

                                </dd>

                            </dl>

                            <div class="clear">

                            </div>