<?php
$z[0]=Array("title","",56,70);
$z[1]=Array("arcurl","",78,93);
$z[2]=Array("litpic","",143,158);
$z[3]=Array("title","",165,179);
$z[4]=Array("title","",188,202);
$z[5]=Array("arcurl","",304,319);
$z[6]=Array("title","",328,342);
$z[7]=Array("title","",360,374);
$z[8]=Array("pubdate","",412,454);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",487,537);
$z[9][4]['function']="cn_substr(@me,200)";

?>