<?php
$z[0]=Array("title","",56,70);
$z[1]=Array("arcurl","",78,93);
$z[2]=Array("litpic","",143,158);
$z[3]=Array("title","",165,179);
$z[4]=Array("title","",188,202);
$z[5]=Array("arcurl","",280,295);
$z[6]=Array("title","",304,318);
$z[7]=Array("title","",336,350);
$z[8]=Array("pubdate","",388,430);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",463,513);
$z[9][4]['function']="cn_substr(@me,200)";

?>