<li class="cooperation">
                <span><a href="[field:typeurl/]">[field:typename/]</a></span>
                <ul>
                  <span><a href="javascript:void(0)">护理</a></span>
                   {dede:channel type='son' noself='yes' }


              [field:typelink/] —— [field:typename/]

               {/dede:channel}
                <!--   <span><a href="javascript:void(0)">护理</a></span>
                  <li><a href="#">护理团队</a></li>
                  <li><a href="#">护理等级</a></li>
                  <li><a href="#">护理特色</a></li>
                  <li><a href="#">护理辅助设施</a></li>
                  <li><a href="#">健康管理</a></li>
                  <li><a href="#">营养膳食</a></li>
                  <li><a href="#">安全保障</a></li>
                </ul>
              </li> -->