<span style="font-size: 24px;font-weight: bold;">关于我们</span>
<span id="span">About</span>
<a  href="[field:arcurl/]"  style="float: right; color: #c2c2c2; font-size: 14px;">NEWS+</a>
</div>
<p class="index_about">常德市福寿颐康园坐落于常德市柳叶湖旅游度假区，是泛湘西北首家集医疗养老，
                       公寓式养老、居家式养老为一体的民办非企业养老机构。是常德市政府重点扶持的养老项目，
                       首期政府划拨建设用地17000平方米，打造省示范型养老基地，紧邻湘雅常德医院。周边环境自然天成
                      ,景色优美、交通便利...
</p>