<li class="cooperation">
                <span><a href="[field:typeurl/]">[field:typename/]</a></span>
                <ul>
                  <span><a href="javascript:void(0)">护理</a></span>
                    {dede:channelartlist  typeid='5'}
                  <li><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></li>
                  {/dede:channelartlist}
                </ul>
              </li>