
<field:lxr itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxr>

<field:sj itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sj>

<field:yj itemname="电子邮件" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:yj>

<field:ms itemname="描述" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:ms>
