<?php
$z[0]=Array("field","",287,306);
$z[0][4]['name']="title";
$z[1]=Array("global","",307,333);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",735,774);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1069,1098);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1470,1499);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n\r\n        <option value=\"list.php?tid=[field:id/]\"> [field:typename/] </option>\r\n\r\n         ",1520,1790);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li> <a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("field","",1890,1909);
$z[6][4]['name']="title";
$z[7]=Array("field","",1937,1989);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("adminname","",1999,2016);
$z[9]=Array("field","\r\n    @me = (strpos(@me,'defaultpic')? \"\" : \"<img src='\".@me.\"'/>\");\r\n    ",2080,2206);
$z[9][4]['name']="litpic";
$z[9][4]['runphp']="yes";
$z[10]=Array("field","",2247,2265);
$z[10][4]['name']="body";
$z[11]=Array("field","",2266,2287);
$z[11][4]['name']="content";
$z[12]=Array("include","",2414,2453);
$z[12][4]['filename']="footer_m.htm";

?>