<?php
$z[0]=Array("title","",68,82);
$z[1]=Array("arcurl","",90,105);
$z[2]=Array("litpic","",173,188);
$z[3]=Array("title","",195,209);
$z[4]=Array("title","",218,232);
$z[5]=Array("arcurl","",361,376);
$z[6]=Array("title","",385,399);
$z[7]=Array("title","",417,431);
$z[8]=Array("pubdate","",483,525);
$z[8][4]['function']="GetDateMK(@me)";
$z[9]=Array("description","",572,622);
$z[9][4]['function']="cn_substr(@me,200)";

?>