<dl class="dl_42">

<dt><a title="[field:title/]" href="[field:arcurl/]" target="_blank">

<img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a></dt>

<dd>

<h5><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h5>

<q>[field:title/]</q>

<p>[field:content function='cn_substr(html2text(@me),800)'/] </p>

</dd>

</dl>

<div class="clear">

</div>

{/dede:list}

</div>

<div class="fenye">
<ol>
{dede:pagelist listitem="info,index,end,pre,next,pageno"listsize=""