<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180828/1-1PRQ00212.png ",93,234);
$z[1][4]['ddimg']="/uploads/allimg/180828/1-1PRQ00212.png";
$z[1][4]['text']="";
$z[1][4]['width']="461";
$z[1][4]['height']="313";
$z[2]=Array("img"," /uploads/allimg/180828/1-1PRQ00217.png ",236,377);
$z[2][4]['ddimg']="/uploads/allimg/180828/1-1PRQ00217.png";
$z[2][4]['text']="";
$z[2][4]['width']="461";
$z[2][4]['height']="313";
$z[3]=Array("img"," /uploads/allimg/180828/1-1PRQ00220.png ",379,520);
$z[3][4]['ddimg']="/uploads/allimg/180828/1-1PRQ00220.png";
$z[3][4]['text']="";
$z[3][4]['width']="461";
$z[3][4]['height']="313";

?>