<?php
$z[0]=Array("item","",4,88);
$z[0][4]['name']="更多模板";
$z[0][4]['link']="http://www.adminbuy.cn";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",92,176);
$z[1][4]['name']="技术支持";
$z[1][4]['link']="http://www.adminbuy.cn";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",180,266);
$z[2][4]['name']="仿站业务";
$z[2][4]['link']="http://fang.adminbuy.cn/";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>