<li class="cooperation">
                <span><a href="[field:typeurl/]">[field:typename/]</a></span>
                <ul>
                  <span><a href="javascript:void(0)">护理</a></span>
                   {dede:type typeid='96,97,98,99,100,101,102'}
                  <li><a href="[field:typeurl/]">[field:typename/]</a></li>
<!--                   <li><a href="#">护理等级</a></li>
                  <li><a href="#">护理特色</a></li>
                  <li><a href="#">护理辅助设施</a></li>
                  <li><a href="#">健康管理</a></li>
                  <li><a href="#">营养膳食</a></li>
                  <li><a href="#">安全保障</a></li> -->