<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/180829/1-1PR9103333.png ",93,248);
$z[1][4]['ddimg']="/uploads/allimg/180829/1-1PR9103333.png";
$z[1][4]['text']="园区环境";
$z[1][4]['width']="455";
$z[1][4]['height']="304";

?>