<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a> | \r\n      ",156,305);
$z[0][4]['row']="7";
$z[0][4]['type']="top";
$z[1]=Array("global","",398,430);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",518,539);
$z[2][4]['name']="cfg_mc";
$z[3]=Array("global","",612,636);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",676,698);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",721,742);
$z[5][4]['name']="cfg_dz";
$z[6]=Array("global","",765,786);
$z[6][4]['name']="cfg_yx";
$z[7]=Array("global","",832,864);
$z[7][4]['name']="cfg_templets_skin";

?>