<?php
$z[0]=Array("global","",536,568);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",715,737);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("field","(@me==\"\")? @me=\" class='cur1'\":@me=\"\";",819,907);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n        ",972,1208);
$z[3][4]['type']="top";
$z[3][4]['row']="9";
$z[3][4]['currentstyle']="<li class='cur1'><a href='~typelink~' >~typename~</a> </li>";

?>