<?php
$z[0]=Array("global","",586,618);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",796,818);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("field","(@me==\"\")? @me=\" class='cur1'\":@me=\"\";",900,988);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n        ",1053,1289);
$z[3][4]['type']="top";
$z[3][4]['row']="9";
$z[3][4]['currentstyle']="<li class='cur1'><a href='~typelink~' >~typename~</a> </li>";
$z[4]=Array("channelartlist","<a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>|",1813,1979);
$z[4][4]['typeid']="15";

?>