<?php
$z[0]=Array("global","",191,223);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",373,405);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel","\r\n        <li><span><a href='[field:typelink/]'>[field:typename/]</a><span></li>\r\n         ",747,968);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='active'>~typename~</a><span></li>";
$z[3]=Array("channelartlist","\r\n        <li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n       ",1089,1259);
$z[3][4]['row']="20";
$z[3][4]['typeid']="93,94,95";
$z[4]=Array("channelartlist","\r\n     <li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n       ",1416,1597);
$z[4][4]['row']="7";
$z[4][4]['typeid']="96,97,98,99,100,101,102";

?>