<?php
$z[0]=Array("global","",232,258);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",780,819);
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("sql","\r\n[field:content/]\r\n   ",2536,2631);
$z[2][4]['sql']="Select content from dede_arctype where id=72";
$z[3]=Array("type"," <a href=\"[field:typelink/]\" class=\"fr\">MORE</a> ",2958,3042);
$z[3][4]['typeid']="20";
$z[4]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" title=\"{dede:field.title/}\" target=\"_blank\">\r\n            <img src=\"[field:picname/]\"/></a>\r\n            <p class=\"clearfix\"><span class=\"fl\"> <em>[field:title/]</em>[field:description function='cn_substr(@me,100)'/]</span></p>\r\n            </a></li>\r\n          ",3161,3528);
$z[4][4]['typeid']="88";
$z[4][4]['row']="4";
$z[4][4]['titlelen']="32";
$z[5]=Array("include","",5064,5103);
$z[5][4]['filename']="footer_m.htm";

?>