<?php
$z[0]=Array("global","",232,258);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",778,817);
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("sql","\r\n    [field:content/]\r\n   ",2592,2692);
$z[2][4]['sql']="Select content from dede_arctype where id=107";
$z[3]=Array("arclist","\r\n          <li><a href=\"list.php?tid=1\" title=\"{dede:field.title/}\" target=\"_blank\">\r\n            <img src=\"[field:picname/]\"/></a>\r\n            <p class=\"clearfix\"><span class=\"fl\"> <em>[field:title/]</em>[field:description function='cn_substr(@me,100)'/]</span></p>\r\n            </a></li>\r\n          ",3203,3570);
$z[3][4]['typeid']="110";
$z[3][4]['row']="6";
$z[3][4]['titlelen']="32";
$z[4]=Array("include","",5063,5102);
$z[4][4]['filename']="footer_m.htm";

?>