<?php
$z[0]=Array("global","",98,130);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",164,185);
$z[1][4]['name']="cfg_mc";
$z[2]=Array("global","",229,251);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",294,315);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("global","",354,375);
$z[4][4]['name']="cfg_qq";
$z[5]=Array("global","",412,433);
$z[5][4]['name']="cfg_yx";
$z[6]=Array("global","",476,497);
$z[6][4]['name']="cfg_dz";

?>