<?php
$z[0]=Array("field","",59,81);
$z[0][4]['name']="typename";
$z[1]=Array("type","\r\n<h5 class='erji' sid='0001,0005,0006'>\r\n<a class=\"ershow\" href=\"[field:typelink/]\" title=\"[field:typename/]\">\r\n[field:typename/]</a></h5>\r\n  ",120,298);
$z[1][4]['typeid']="56";
$z[2]=Array("type","\r\n<h5 class='erji' sid='0001,0005,0006'>\r\n<a class=\"ershow\" href=\"[field:typelink/]\" title=\"[field:typename/]\">\r\n[field:typename/]</a></h5>\r\n",306,482);
$z[2][4]['typeid']="57";

?>