<?php
$z[0]=Array("field","",342,361);
$z[0][4]['name']="title";
$z[1]=Array("global","",362,388);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",733,772);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1059,1088);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1474,1503);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n       \r\n        <option value=\"list.php?tid=[field:id/]\"> [field:typename/] </option>\r\n        \r\n         ",1532,1817);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li> <a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("list","\r\n      <li> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">[field:title/]<span class=\"fr\">[field:pubdate function=\"MyDate('m-d',@me)\"/] </span></a> </li>\r\n      ",1900,2123);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="50";
$z[7]=Array("pagelist","",2257,2328);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2427,2466);
$z[8][4]['filename']="footer_m.htm";

?>