<?php
$z[0]=Array("field","",229,248);
$z[0][4]['name']="title";
$z[1]=Array("global","",249,275);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",737,776);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1063,1092);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1466,1495);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n       \r\n        <option value=\"list.php?tid=[field:id/]\"> [field:typename/] </option>\r\n        \r\n         ",1524,1809);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li> <a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("list","\r\n    <li> <a href=\"view.php?aid=[field:id/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\">\r\n      <p class=\"title\">[field:title/]</p>\r\n      <span class=\"title bg\"></span> </a> </li>\r\n    ",1884,2114);
$z[6][4]['pagesize']="9";
$z[7]=Array("pagelist","",2205,2276);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2343,2382);
$z[8][4]['filename']="footer_m.htm";

?>