<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('84', '/uploads/allimg/180831/1-1PS115191M37.jpg');
$maNum = 1;
$myaddons[$maNum] = array('85', '/uploads/allimg/180831/1-1PS1152454509.jpg');
$maNum = 2;
$myaddons[$maNum] = array('86', '/uploads/allimg/180831/1-1PS11525513M.jpg');
$maNum = 3;
$myaddons[$maNum] = array('87', '/uploads/allimg/180831/1-1PS1153U2J9.jpg');
$maNum = 4;
$myaddons[$maNum] = array('88', '/uploads/allimg/180831/1-1PS115395S21.jpg');
$maNum = 5;
